#!/bin/bash

mysql=`which mysql`

export MYSQL_PWD

DB_DEST_DBFILE=$1
DB_DEST_DBNAME=${DB_DEST_DBFILE%%.*}
DB_DEST_EXT=${DB_DEST_DBFILE##*.}
DB_DEST_USER="root"
DB_DEST_HOST=""
DB_DEST_PORT=""

function checking_vars {
  echo -n "* Checking if needed vars are set... "
    ERROR_MSG=""
  		if [ -z "$DB_DEST_DBNAME" ]; then ERROR_MSG="$ERROR_MSG NO DB_DEST_DBNAME";fi
  		if [ -z "$DB_DEST_USER" ]; then ERROR_MSG="$ERROR_MSG NO DB_DEST_USER";fi
  		if [ -z "$DB_DEST_HOST" ]; then DB_DEST_HOST="localhost";fi
      if [ -z "$DB_DEST_PORT" ]; then DB_DEST_PORT="3306";fi
  		if [ ! -z "$ERROR_MSG" ]; then fatal "$ERROR_MSG";fi
  	echo "DONE"
}

function checking_mysql {
  echo -en "* Checking mysql... "
  if ! type "$mysql" > /dev/null; then
    echo "mysql does not exist. Try apt install mysql-client"; exit 0
  fi
  echo "DONE"
}

function checking_connexion {
  read -s -p "Enter MYSQL root password: " MYSQL_PWD; echo
  while ! $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER -p"$MYSQL_PWD" -e ";" 2>/dev/null ; do
    read -s -p "Can't connect, please retry: " MYSQL_PWD; echo
  done
}

function checking_database {
  echo -n "* Checking if the requested database exists... ";
  DB_EXIST=0
  DBS=`$mysql -u $DB_DEST_USER -h $DB_DEST_HOST -Bse 'show databases'| egrep -v 'information_schema|$mysql'`
  for db in $DBS; do
  	if [ "$db" = "$DB_DEST_DBNAME" ]; then DB_EXIST=1; fi;
  done
  if [ "$DB_EXIST" = "1"  ]; then
    echo -n "YES, overwrite? 'y/n': "
  	read DOWEPURGE
    case "$DOWEPURGE" in
    	'y')
  		mysql_db_drop
  		OVERRIDEUSERCREATION="true"
  		;;
    	*)
    		echo "$DB_DEST_DBNAME has not been dropped."; exit 0
    		;;
  	esac
  else
    echo "NO"
  fi
}

function mysql_user_drop {
  echo -n "* Drop user... "
  $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER -e "DROP USER '$DB_DEST_DBNAME'@'localhost';"
  echo -n "DONE"; echo
}

function mysql_user_create {
  echo -n "* Create user... "
  $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER -e "CREATE USER '$DB_DEST_DBNAME'@'localhost' IDENTIFIED BY '$DB_DEST_DBNAME';"
  echo -n "DONE"; echo
}

function mysql_user_grant {
  echo -n "* Grant permission... "
  $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER -e "GRANT ALL PRIVILEGES ON '$DB_DEST_DBNAME'.* TO '$DB_DEST_DBNAME'@'localhost' IDENTIFIED BY '$DB_DEST_DBNAME';"
  $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER -e "FLUSH PRIVILEGES;"
  echo -n "DONE"; echo
}

function mysql_db_drop {
  echo -n "* Purge database... "
  $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER -e "DROP DATABASE \`$DB_DEST_DBNAME\`;"
  echo -n "DONE"; echo
}

function mysql_db_create {
  echo -n "* Creating database ... "
  $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER -e "CREATE DATABASE IF NOT EXISTS \`$DB_DEST_DBNAME\` CHARACTER SET utf8 COLLATE utf8_general_ci;"
  echo "DONE"
  echo -n "* Fill database... "
  case "$DB_DEST_EXT" in
    sql)
      cat $DB_DEST_DBFILE | $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER $DB_DEST_DBNAME
      echo -n "DONE"; echo;;

    gz)
      zcat $DB_DEST_DBFILE | $mysql -h $DB_DEST_HOST -P $DB_DEST_PORT -u $DB_DEST_USER $DB_DEST_DBNAME
      echo -n "DONE"; echo;;

    *)  usage;exit 0;;
  esac
}

case $1 in
    -h|help)
      echo "Usage: `basename $0` dump.sql[.gz] "
      exit 0;;
    *.sql|*.gz)
      checking_vars
      checking_mysql
      checking_connexion
      checking_database
      mysql_db_create
      ;;
    *)
      echo "Argument not match"
      exit 0;;
esac
